/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalysRouteImport } from './routes/analys'
import { Route as KonsolRouteImport } from './routes/konsol'
import { Route as LoggaInRouteImport } from './routes/logga-in'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysRoute = AnalysRouteImport.update({
  id: '/analys',
  path: '/analys',
  getParentRoute: () => rootRouteImport,
} as any)
const KonsolRoute = KonsolRouteImport.update({
  id: '/konsol',
  path: '/konsol',
  getParentRoute: () => rootRouteImport,
} as any)
const LoggaInRoute = LoggaInRouteImport.update({
  id: '/logga-in',
  path: '/logga-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/konsol': typeof KonsolRoute
  '/logga-in': typeof LoggaInRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/konsol': typeof KonsolRoute
  '/logga-in': typeof LoggaInRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analys': typeof AnalysRoute
  '/konsol': typeof KonsolRoute
  '/logga-in': typeof LoggaInRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/analys' | '/konsol' | '/logga-in'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analys' | '/konsol' | '/logga-in'
  id: '__root__' | '/' | '/analys' | '/konsol' | '/logga-in'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysRoute: typeof AnalysRoute
  KonsolRoute: typeof KonsolRoute
  LoggaInRoute: typeof LoggaInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analys': {
      id: '/analys'
      path: '/analys'
      fullPath: '/analys'
      preLoaderRoute: typeof AnalysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konsol': {
      id: '/konsol'
      path: '/konsol'
      fullPath: '/konsol'
      preLoaderRoute: typeof KonsolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logga-in': {
      id: '/logga-in'
      path: '/logga-in'
      fullPath: '/logga-in'
      preLoaderRoute: typeof LoggaInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysRoute: AnalysRoute,
  KonsolRoute: KonsolRoute,
  LoggaInRoute: LoggaInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
